# Generated by Django 2.2.5 on 2021-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favlist',
            name='books',
            field=models.ManyToManyField(related_name='favlists', to='books.Book'),
        ),
    ]
